apiVersion: skaffold/v2beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: stephengrider/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
    - image: cygnetops/multi-server-pgfix-5-11
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
            - src: "**/*.js"
              dest: .
    - image: stephengrider/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
            - src: "**/*.js"
              dest: .
deploy:
  kubectl:
    manifests:
        - k8s/client-deployment.yaml
        - k8s/server-deployment.yaml
        - k8s/worker-deployment.yaml
        - k8s/database-persistent-volume-claim.yaml
        - k8s/ingress-service.yaml
        - k8s/postgres-cluster-ip-service.yaml
        - k8s/postgres-deployment.yaml
        - k8s/redis-cluster-ip-service.yaml
        - k8s/redis-deployment.yaml
        - k8s/worker-deployment.yaml
        - k8s/server-cluster-ip-service.yaml
        - k8s/client-cluster-ip-service.yaml